repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
  - repo: https://github.com/prettier/prettier
    rev: 2.1.2
    hooks:
      - id: prettier
        files: \.(css|less|scss|ts|tsx|graphql|gql|js|jsx|md)$
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.13.0-1
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@7.0.0
          - eslint-plugin-prettier@3.1.3
          - prettier@2.0.5
